version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  
  db:
    image: mysql:9.5.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-u","root","-p{DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"